sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: IudVzFmlG4Y3EphWMOmT4SuqkwnSf/iV2rrrrSVDDgXOi3tgTWoILVhQZKvXz+PrwMld+/eIomImYTJ0ALocFBUI74+ihH5021TPNHAgFr8z04cOlBWkdvNV0JzNqO9c3KR/5w9ow4zwzjwTe39XwAwY5qx+rMM+JD/7Gr13I1Qo68ntU8rA6Cj9hGoah80gsZUDTjCOolOWcjJHu8y0c4INg1MhTf8eTgA1MsLvA/IDJEW2ujTHxPAyCnFKOzaDY6RCKZigLfidlvyh//11TonleFFKhnJ4BuKSXQAwhSUoz4DJ3d2rD+UswaIUg4e6Fe4We7GiCgeaYqLyn8Bdl8rm5q5nwSQ6m66amb05hCfHlKHsj7nfV5/9rAFifHAoIy0D36b8bLQGUiag9tDcDKZqXCwgA4fJmIAlMzwUUPgfrBu+2eZKiTVaNll4RtLhkjoL6HCt6IJ9G8XejvkJClHOb9TyQTaCNLqDj1/LcP+fQFEm7sCVI4RbPeKCogoXBqmam5u+rF4WA61oT9pCc/Fi0I7ETUBUujpvhb9YGE33GHW42FJ0tdlENuF9A1w+ZoBpmznTTnZz9PiLPecr9M5UK4WFWk+cla1+PbdGWaONQuUzDWewA8J5Q4VHdTWwchjhv3FcjyWG0V5uO+U+3aMRJOVmIqHygD5RydZXilI=
